[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
scikit-learn = "^1.4.2"
tqdm = "^4.66.4"
tensorflow = "^2.16.1"
numba = "^0.60.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
